client.go, margin_info.go, margin_info_test.go
=> Fix MarginInfo

client.go
Get rid of "Nonce is too small" error.
=> Changed nonce to UnixNano

account.go, account_test.go, balances.go, client.go, credits.go, deposit.go, deposit_test.go, history.go, history_test.go, lendbook.go, lendbook_test.go, margin_funding.go, margin_funding_test.go, margin_info.go, margin_info_test.go, order_book.go, order_book_test.go, orders.go, pairs.go, pairs_test.go, positions.go, positions_test.go, stats.go, stats_test.go, ticker.go, ticker_test.go, trades.go, trades_test.go
Implements:
- add tests
- ticker
- stats
- positions refactoring with claim position
- trades 
- detailed pairs
- orderbook tests and refactoring
- deposits
- history
- margin funding
=> Implement missing API endpoints

account.go, balances.go, client.go, credits.go, deposit.go, deposit_test.go, history.go, lendbook.go, margin_funding.go, margin_info.go, offers.go, offers_test.go, order_book.go, orders.go, orders_test.go, pairs.go, pairs_test.go, positions.go, stats.go, ticker.go, trades.go, wallet.go, wallet_test.go, websocket.go
This PR switches to private internal functions and add more API endpoints.
=> add more endpoints

websocket.go
Added these new currency pairs as they are included in `GET /v1/symbols`
=> Added ETH websocket pairs

client.go, websocket.go
- fixes #19 
- add missing pairs
=> Fix default endpoints

examples/account/main.go, examples/orders/main.go, examples/ws-private/main.go, tests/integration/order_book_test.go
=> fix test and examples - go fmt

examples/v1/ws-book/main.go, utils/nonce.go, v1/client.go, v1/websocket.go
Again, most of these changes are cosmetic to appease `golint` but I've also moved the `getNonce` function into the `utils` package for now and changed it to use an actual random nonce instead of a fairly predictable counter.
=> moves getNonce into the newly created utils package and uses proper cryptographic randomness instead of just a simple counter.

v1/orders.go, v1/orders_test.go
These are again mostly cosmetic changes but also change the type of the order id in accordance with the documentation.
=> clean up the orders service and changes the order ID to int64

utils/nonce.go, v1/client.go, v1/websocket.go
This should fix the regression introduced for the nonce creation.
=> fix the nonce producer

v1/client.go, v1/positions.go
- Fix compile error, new getNonce() doesn't return error
- Fix Positions.All() since it's supposed to be a POST
=> Fix Nonce and Positions

v1/positions.go
=> positionId is int not string

v1/websocket.go
=> Handle heartbeat messages sent over an authenticated websocket connection

examples/v2/ws-book/main.go, examples/v2/ws-private/main.go, tests/integration/v2/mock_async.go, v2/websocket/client.go, v2/websocket/transport.go
added support for reconnecting using the bitfinex go API. also added the read timeout pass-through to websocket.
=> Reconnects

tests/integration/v2/listener.go, tests/integration/v2/live_websocket_public_test.go, tests/integration/v2/mock_async.go, tests/integration/v2/mock_ws_private_test.go, tests/integration/v2/mock_ws_public_test.go, tests/integration/v2/socket_timeout_test.go, tests/integration/v2/test_ws_service.go, v2/rest/trades.go, v2/types.go, v2/websocket/api.go, v2/websocket/channels.go, v2/websocket/client.go, v2/websocket/subscriptions.go, v2/websocket/transport.go
Updates for improved processing of public channel messages. Included precision and frequency parameters for the book updates API call.
=> Public channel updates

tests/integration/v2/api_test.go, tests/integration/v2/socket_timeout_test.go, v2/websocket/api.go, v2/websocket/client.go, v2/websocket/events.go
for ping support, this will be helpful in other adapters which send generic messages pre-refactor
=> introduced raw generic message publishing and ping support

tests/integration/v2/reconnect_test.go, v2/websocket/client.go, v2/websocket/subscriptions.go
replace heartbeat timer with channel construct, cleaner impl and less buggy with golang timer cancel function races
=> Replace timer

tests/integration/v2/reconnect_test.go, tests/integration/v2/test_ws_service.go, v2/websocket/parameters.go, v2/websocket/subscriptions.go
increase default hb timeout to 10s (still configurable).
increased test speed.  also increased startup speed
=> Hb increase

examples/v2/book-feed/main.go, tests/integration/v2/live_websocket_public_test.go, tests/integration/v2/reconnect_test.go, v2/websocket/api.go, v2/websocket/channels.go, v2/websocket/client.go, v2/websocket/parameters.go, v2/websocket/subscriptions.go, v2/websocket/transport.go
- add Len parameter to book subscriptions in API
- simplify heartbeat threading model
- improve test runtime speed
- increased default shutdown timeout to 3 seconds (only affects process exit)
=> Book subscriptions, improved heartbeats

v2/rest/transport.go
=> Fixed build error

v2/rest/client.go, v2/rest/transport.go
There are a number of small but critical issues with the v2 rest client preventing it from working
* fix typo in header name
* fix headers not being added to http request
* fix error message being swallowed
* fix empty data message signing (credit to https://github.com/Investabit/bitfinex-api-go/commit/7d487f0d091d8f4e46374f0df030339ed21c87f7)
@brobits @prdn I broke these out from anything else, should be straightforward to review.
=> Critical rest client fixes

examples/v2/rest-orders/main.go, v2/rest/client.go, v2/rest/orders.go, v2/types.go
- exchange stop limit support
- REST order trades support
- REST custom nonce support
=> added exchange stop limit & rest order trades support

.travis.yml, tests/integration/v2/reconnect_test.go, v2/types.go
Adds .travis.yml file, increased delay time in test to allow system a chance to reconnect, and addresses an issue in a print statement
=> Unit Test Updates and minor change to allow Travis CI build to pass.

readme.md
Update readme: `bitfinex.ORDER_TYPE_EXCHANGE_LIMIT` to `bitfinex.OrderTypeExchangeLimit`
=> Update readme: Order Create - OrderType

v1/pairs.go, v1/pairs_test.go
Fixed a typo, tests and new field added.
=> Some fields in symbols details request fixed

examples/v2/ws-update-order/main.go, tests/integration/v2/listener.go, tests/integration/v2/mock_ws_private_test.go, v2/types.go, v2/websocket/api.go, v2/websocket/channels.go, v2/websocket/client.go, v2/websocket/factories.go, v2/websocket/orderbook.go
This pull request ats the capability to update existing orders using `client.SubmitUpdateOrder` plus an example usage and unit testing.
=> Add update order to v2 ws

tests/integration/v2/listener.go, tests/integration/v2/live_websocket_public_test.go, tests/integration/v2/mock_ws_private_test.go, tests/integration/v2/mock_ws_public_test.go, tests/integration/v2/reconnect_test.go, tests/integration/v2/test_ws_service.go, travis.yml, v1/client.go, v1/orders.go, v1/pairs_test.go, v1/websocket.go, v2/convert.go, v2/rest/client.go, v2/types.go, v2/websocket/channels.go, v2/websocket/client.go, v2/websocket/events.go, v2/websocket/subscriptions.go
- Fixes up a ton of linting errors
- Adds travis for lint and unit test checking
=> Add travis cli

v2/types.go
=> Include missing time in force on order update object

examples/v2/rest-orders/main.go, v1/client.go, v2/rest/client.go, v2/websocket/client.go
Edit all version 2 endpoints from `api.bitfinex.com` to `api-pub.bitfinex.com`
=> Switch all v2 endpoints to api-pub

v2/rest/client.go, v2/rest/ledgers.go, v2/types.go
- v2/rest: adds support for ledger endpoint
=> Adding LedgerService

examples/v2/rest-currencies/main.go, examples/v2/rest-public-trades/main.go, examples/v2/rest-stats/main.go, v2/rest/candles.go, v2/rest/client.go, v2/rest/currencies.go, v2/rest/stats.go, v2/rest/trades.go, v2/types.go, v2/websocket/subscriptions.go
Adds new functions
- `client.Trades.PublicHistoryWithQuery` gets public trades
- `client.Trades.AccountHistoryWithQuery` gets private account trades
- `client.Stats.FundingHistory` get funding history stats
- `client.Stats.FundingLast` get last funding stat
- `client.Stats.CreditSizeHistory` get credit size history stats
- `client.Stats.CreditSizeLast` get last credit size stat
- `client.Stats.SymbolCreditSizeHistory` gets credit size history for symbol
- `client.Stats.SymbolCreditSizeLast` gets last credit size for symbol
- `client.Stats.PositionHistory` gets position history stats
- `clients.Stats.PositionLast` gets last position stat
- `clients.Currency.Conf` gets the currency config
=> Add new v2 functions

.github/ISSUE_TEMPLATE, .github/PULL_REQUEST_TEMPLATE
This pull request adds pull request and issue templates
=> Improve pre-commit vetting

v2/types.go
Adds leverage field to order new and order update
=> Add leverage field to order new and order update

v2/types.go
Cleaned up debug print statements
=> Cleaned up debug print statements

readme.md, v2/websocket/client.go
=> Fix upstream listen warning args

v2/rest/funding.go, v2/rest/positions.go
=> chore: remove print

v2/types.go
Fix v2 rest ticker API funding result error
- None
- None
=> Fix V2 Rest ticker API funding result error

v2/websocket/channels.go, v2/websocket/client.go
Fix candidate for #218 
- Fix panic: send on closed channel
=> Fix: discard messages received after Close() was called
